### ISSUE TITLE
Connection not working

### ISSUE THREAD

**Issue by wityan** [WeTransfer/wt-js-sdk#118]
I added this code and I get this error message: wetransfer.min.js:126 Uncaught (in promise) WTError: The authorization call failed and no usable JWT could be found there. Please check your API Key.

**Input Code**

```js
const createWTClient = require('@wetransfer/js-sdk');

(async function() {
    const apiClient = await createWTClient('vKDFBOB7LQ1s8O64Rri9I7UgbHWyHXZP5YCUa1GP', {
        logger: {
            level: 'silly'
        }
    });

    const transfer = await apiClient.transfer.create({
        name: 'My very first transfer!'
    });
    console.log(transfer);
})();
```

**Comment by arkaitzgarro** [comment]
Hi @wityan,

Can you specify which version of the SDK are you using? And version of `node` as well?

I just tried this exact code and works on my machine: `@wetransfer/js-sdk@0.6.0` and `node v8.11.3`

**Comment by arkaitzgarro** [comment]
Hi again,

We don't have CORS enabled at that point on our API. We don't expect browser to connect directly to our API, because it means you are exposing your API Key to the wild, but we understand that this is something our user will do anyway, at their own risk.

We will need some time to enable CORS and make it available on production environment, but it is on the top of our priority list. We will start working on it on Monday.

I will let you know when it's ready.

**Comment by arkaitzgarro** [comment]
Hi @wityan,

I'm glad to say that we've just released a new version of the API, that not supports CORS. You can find the new documentation here: https://developers.wetransfer.com/documentation

Also, the JS SDK has been updated to v1.0.0, to support the new API.

I'm closing this issue because in principle the issue must be solved if you use the new API.
