### ISSUE TITLE
File hashes

### ISSUE THREAD

**Issue by overlookmotel** [WeTransfer/wt-js-sdk#142]
**Is your feature request related to a problem? Please describe.**

When uploading files, to ensure data integrity, it would be great to be able to provide a hash (either for each chunk, or the file as a whole), and for that hash to be checked at the receiving end. If the hash doesn't match, an error should be thrown, so can retry sending.

**Additional context**

I would be happy to implement this, if it were supported by the WeTransfer API.

I assume that files are hashed in storage anyway, so this would be a matter of exposing that info through the API.

**Comment by arnoFleming** [comment]
Currently we do not calculate the hashes of files in storage, so we have no easy way to test them against your pre-calculated values. 

That means that you're on your own for checking data integrity.

*Alternative*
A potential work around for this issue is calculating hashes before transfer, and storing those hashes in a file. 
On retrieval, the end user could check if the pre-calculated hashes of the files match with the hashes of the files s/he downloaded. 
Downside of the workaround is that you're depending on the end user. The upside is that it tests the data integrity of the whole transfer proces.

See [this `sha1sum` tutorial](https://shapeshed.com/unix-sha1sum/) if you want to go this route.
