### ISSUE TITLE
Add function to download a file from a transfer URL

### ISSUE THREAD

**Issue by olokobayusuf** [WeTransfer/wt-js-sdk#203]
**Is your feature request related to a problem? Please describe.**
It's not a problem, but a worthwhile feature request. This API is one-way, only offering ways to upload files. It'll be great to also have a way to download a file to a buffer. [People have done it](https://github.com/superalex/py-wetransfer), but it'll be great to have in the official SDK like Dropbox.

**Describe the solution you'd like**
Something along the lines of:
```typescript
const downloadMetadata = await WeTransfer.transfer.downloadTransfer({ url: ... });
// Do stuff with `downloadMetadata.buffer/contents`
```

**Describe alternatives you've considered**
Using a hacky solution, like the link I referenced earlier.

**Additional context**

**Comment by arkaitzgarro** [comment]
Unfortunately, we don't have plans to implement this feature in the near future. Not for the Public API, nor for any of the official SDKs. The existing solution you pointed out is using an old and _private_ API, and probably violates our Terms of Service.

I'm closing this issue since there's nothing we can do. I will let you know if the situation changes somehow.

**Comment by olokobayusuf** [comment]
Sounds good. My intended use case is to programmatically download files from a WeTransfer link. I recall a `findTransfer` method. Can this be used instead?
